# Generated by Django 5.1.1 on 2024-10-09 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dasapp', '0017_alter_customuser_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[(1, 'admin'), (2, 'doc')], default=1, max_length=50),
        ),
    ]
