# Generated by Django 3.1.6 on 2024-10-19 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dasapp', '0021_auto_20241019_2125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[(1, 'admin'), (2, 'doc')], default=1, max_length=50),
        ),
    ]
