# Generated by Django 5.1.2 on 2024-10-20 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dasapp', '0024_payment_alter_appointment_id_alter_customuser_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.IntegerField(),
        ),
    ]
