# Generated by Django 5.1.2 on 2024-10-20 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dasapp', '0025_alter_payment_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[(2, 'doc'), (1, 'admin')], default=1, max_length=50),
        ),
        migrations.AlterField(
            model_name='payment',
            name='expirydate',
            field=models.IntegerField(),
        ),
    ]
