# Generated by Django 5.1.2 on 2024-10-20 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dasapp', '0026_alter_customuser_user_type_alter_payment_expirydate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='patientname',
        ),
        migrations.AddField(
            model_name='payment',
            name='patient_name',
            field=models.TextField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='payment',
            name='cardnumber',
            field=models.TextField(blank=True, default=0),
        ),
    ]
