# Generated by Django 5.1.2 on 2024-10-20 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dasapp', '0027_remove_payment_patientname_payment_patient_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='patient_name',
            field=models.CharField(max_length=250),
        ),
    ]
