# Generated by Django 4.1.13 on 2024-10-21 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dasapp', '0028_alter_payment_patient_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='cardnumber',
            new_name='cardnumbers',
        ),
    ]
