# Generated by Django 4.1.13 on 2024-10-23 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dasapp', '0029_rename_cardnumber_payment_cardnumbers'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='address',
            field=models.CharField(default='Unknown', max_length=200),
        ),
        migrations.AddField(
            model_name='appointment',
            name='age',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='appointment',
            name='appointmenttype',
            field=models.CharField(default='Unknown', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='appointment',
            name='gender',
            field=models.CharField(default='kapan', max_length=100),
            preserve_default=False,
        ),
    ]
