# Generated by Django 4.1.13 on 2024-10-24 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dasapp', '0035_alter_payment_cardnumbers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='expirydate',
            field=models.DateField(null=True),
        ),
    ]
