# Generated by Django 4.1.13 on 2024-10-24 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dasapp', '0036_alter_payment_expirydate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='age',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='payment',
            name='cardnumbers',
            field=models.BigIntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='payment',
            name='expirydate',
            field=models.CharField(default=0, max_length=10),
        ),
    ]
