# Generated by Django 4.1.13 on 2024-10-24 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dasapp', '0042_alter_customuser_user_type_alter_payment_cardnumbers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='age',
            field=models.IntegerField(default=0, max_length=2),
        ),
        migrations.AlterField(
            model_name='payment',
            name='expirydate',
            field=models.CharField(max_length=10),
        ),
    ]
