# Generated by Django 4.1.13 on 2024-10-24 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dasapp', '0043_alter_appointment_age_alter_payment_expirydate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='age',
            field=models.IntegerField(default=0),
        ),
    ]
