# Generated by Django 4.1.13 on 2024-10-24 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dasapp', '0044_alter_appointment_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[(1, 'admin'), (2, 'doc')], default=1, max_length=50),
        ),
        migrations.AlterField(
            model_name='payment',
            name='cardnumbers',
            field=models.BigIntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='expirydate',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
