# Generated by Django 4.1.13 on 2024-10-24 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dasapp', '0049_alter_customuser_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='cardnumbers',
            field=models.CharField(default=0, max_length=255),
        ),
    ]
