# Generated by Django 4.1.13 on 2024-10-24 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dasapp', '0053_alter_payment_cardnumbers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='cardnumbers',
            field=models.CharField(blank=True, default='Not Provided', max_length=255, null=True),
        ),
    ]
