# Generated by Django 4.1.13 on 2024-10-24 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dasapp', '0054_alter_payment_cardnumbers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='cardnumbers',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
