# Generated by Django 4.1.13 on 2024-10-27 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dasapp', '0072_alter_appointment_date_of_appointment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='date_of_appointment',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='time_of_appointment',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[(2, 'doc'), (1, 'admin')], default=1, max_length=50),
        ),
    ]
