# Generated by Django 4.1.13 on 2024-10-27 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dasapp', '0075_alter_appointment_time_of_appointment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='time_of_appointment',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
