# Generated by Django 4.1.13 on 2024-10-27 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dasapp', '0076_alter_appointment_time_of_appointment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='time_of_appointment',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[(1, 'admin'), (2, 'doc')], default=1, max_length=50),
        ),
    ]
