# Generated by Django 3.2.20 on 2024-11-02 09:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dasapp', '0077_alter_appointment_time_of_appointment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='arrival_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='appointment',
            name='burst_time',
            field=models.IntegerField(default=30),
        ),
        migrations.AddField(
            model_name='appointment',
            name='priority',
            field=models.IntegerField(choices=[(1, 'Emergency'), (2, 'High Priority'), (3, 'Standard')], default=3),
        ),
        migrations.AddField(
            model_name='appointment',
            name='waiting_time',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[(2, 'doc'), (1, 'admin')], default=1, max_length=50),
        ),
    ]
