# Generated by Django 3.2.20 on 2024-11-10 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dasapp', '0078_auto_20241102_1533'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='arrival_time',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='burst_time',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='priority',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='waiting_time',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[(1, 'admin'), (2, 'doc')], default=1, max_length=50),
        ),
    ]
